param(
    [string]$ProductionRepo = "C:\Timelapse-OAI",
    [string]$ProductionData = "C:\timelapse-data",
    [string]$DevData = "C:\timelapse-data-dev",
    [switch]$CopyProductionState
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
$EnvPath = Join-Path $RepoRoot ".env.dev-windows"
$EnvExamplePath = Join-Path $RepoRoot "env\windows-dev.env.example"
$ComposeArgs = @(
    "--env-file", $EnvPath,
    "-f", (Join-Path $RepoRoot "docker-compose.yml"),
    "-f", (Join-Path $RepoRoot "docker-compose.dev.yml")
)

function Read-DotEnv([string]$Path) {
    $values = [ordered]@{}
    if (-not (Test-Path $Path)) { return $values }
    foreach ($line in Get-Content $Path) {
        $trimmed = $line.Trim()
        if ($trimmed.Length -eq 0 -or $trimmed.StartsWith("#") -or -not $trimmed.Contains("=")) { continue }
        $parts = $trimmed.Split("=", 2)
        $values[$parts[0]] = $parts[1]
    }
    return $values
}

function Write-DotEnv([string]$Path, [System.Collections.IDictionary]$Values) {
    $lines = @(
        "# Generated by scripts/windows-dev-deploy.ps1 for side-by-side Windows dev.",
        "# Safe defaults keep this stack off production ports and data.",
        ""
    )
    foreach ($key in $Values.Keys) {
        $lines += "$key=$($Values[$key])"
    }
    Set-Content -Path $Path -Value $lines -Encoding ascii
}

function Normalize-PathText([string]$Value) {
    return ($Value -replace "\\", "/").TrimEnd("/").ToLowerInvariant()
}

function Require-Value([System.Collections.IDictionary]$Values, [string]$Key) {
    if (-not $Values.Contains($Key) -or [string]::IsNullOrWhiteSpace([string]$Values[$Key])) {
        throw "$Key is missing from $EnvPath. Fill it before deploying."
    }
}

function Ensure-DevEnv() {
    if (Test-Path $EnvPath) { return }
    if (-not (Test-Path $EnvExamplePath)) { throw "Missing $EnvExamplePath" }

    $values = Read-DotEnv $EnvExamplePath
    $prodEnvPath = Join-Path $ProductionRepo ".env"
    if (Test-Path $prodEnvPath) {
        $prodValues = Read-DotEnv $prodEnvPath
        foreach ($key in @(
            "ADMIN_USERNAME",
            "ADMIN_PASSWORD_HASH",
            "SESSION_SECRET",
            "CRED_ENC_KEY",
            "SESSION_HTTPS_ONLY",
            "FFMPEG_GUARD_RATIO",
            "FFMPEG_GUARD_MARGIN_MIN_SEC",
            "FFMPEG_GUARD_MARGIN_MAX_SEC"
        )) {
            if ($prodValues.Contains($key) -and -not [string]::IsNullOrWhiteSpace([string]$prodValues[$key])) {
                $values[$key] = $prodValues[$key]
            }
        }
    }

    $values["COMPOSE_PROJECT_NAME"] = "timelapse-dev"
    $values["TIMELAPSE_DATA_DIR"] = ($DevData -replace "\\", "/")
    $values["WEB_PORT"] = "18080"
    $values["WORKER_REST_PORT"] = "18081"
    $values["WORKER_GATEWAY_PORT"] = "18082"
    $values["WORKER_GRPC_PORT"] = "15051"
    $values["WEB_CONTAINER_NAME"] = "timelapse-clean-web"
    $values["WORKER_CONTAINER_NAME"] = "timelapse-clean-worker"
    $values["WORKER_GRPC_CONTAINER_NAME"] = "timelapse-clean-worker-grpc"
    $values["WORKER_GATEWAY_CONTAINER_NAME"] = "timelapse-clean-worker-gateway"
    $values["WORKER_BASE_URL"] = "http://worker-gateway:8082"
    $values["WORKER_GRPC_ADDR"] = "worker-grpc:50051"
    $values["WORKER_REST_URL"] = "http://worker:8081"
    $values["PLAYWRIGHT_APP_HOST"] = "http://timelapse:8080"

    Write-DotEnv $EnvPath $values
    Write-Host "Created $EnvPath"
}

function Assert-SafeDevEnv() {
    $values = Read-DotEnv $EnvPath
    foreach ($key in @("ADMIN_PASSWORD_HASH", "SESSION_SECRET", "CRED_ENC_KEY")) {
        Require-Value $values $key
    }

    $dataDir = Normalize-PathText ([string]$values["TIMELAPSE_DATA_DIR"])
    $prodData = Normalize-PathText $ProductionData
    $devDataNorm = Normalize-PathText $DevData
    if ($dataDir -eq $prodData) {
        throw "Refusing to deploy: TIMELAPSE_DATA_DIR points at production data ($ProductionData)."
    }
    if ($dataDir -ne $devDataNorm) {
        throw "Refusing to deploy: TIMELAPSE_DATA_DIR must be $($DevData -replace '\\','/') for this side-by-side run."
    }

    $expected = [ordered]@{
        WEB_PORT = "18080"
        WORKER_REST_PORT = "18081"
        WORKER_GATEWAY_PORT = "18082"
        WORKER_GRPC_PORT = "15051"
        WEB_CONTAINER_NAME = "timelapse-clean-web"
        WORKER_CONTAINER_NAME = "timelapse-clean-worker"
        WORKER_GRPC_CONTAINER_NAME = "timelapse-clean-worker-grpc"
        WORKER_GATEWAY_CONTAINER_NAME = "timelapse-clean-worker-gateway"
    }
    foreach ($key in $expected.Keys) {
        if (-not $values.Contains($key) -or [string]$values[$key] -ne [string]$expected[$key]) {
            throw "Refusing to deploy: $key must be $($expected[$key]) for this side-by-side run."
        }
    }
}


function Wait-Http([string]$Url, [string]$Name, [int]$TimeoutSeconds = 90) {
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    do {
        try {
            $response = Invoke-WebRequest -UseBasicParsing -Uri $Url -TimeoutSec 5
            if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500) {
                Write-Host "$Name is reachable at $Url (HTTP $($response.StatusCode))"
                return
            }
        } catch {
            Start-Sleep -Seconds 2
            continue
        }
        Start-Sleep -Seconds 2
    } while ((Get-Date) -lt $deadline)
    throw "$Name did not become reachable at $Url within $TimeoutSeconds seconds."
}

function Wait-Tcp([string]$HostName, [int]$Port, [string]$Name, [int]$TimeoutSeconds = 90) {
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    do {
        $client = New-Object System.Net.Sockets.TcpClient
        try {
            $async = $client.BeginConnect($HostName, $Port, $null, $null)
            if ($async.AsyncWaitHandle.WaitOne(2000, $false)) {
                $client.EndConnect($async)
                Write-Host "$Name is accepting TCP connections on ${HostName}:$Port"
                return
            }
        } catch {
            Start-Sleep -Seconds 2
        } finally {
            $client.Close()
        }
    } while ((Get-Date) -lt $deadline)
    throw "$Name did not accept TCP connections on ${HostName}:$Port within $TimeoutSeconds seconds."
}

function Backup-And-CopyState() {
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $backupRoot = Join-Path "C:\timelapse-backups" "dev-deploy-$timestamp"
    New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null

    $prodEnvPath = Join-Path $ProductionRepo ".env"
    if (Test-Path $prodEnvPath) {
        Copy-Item $prodEnvPath (Join-Path $backupRoot "production.env") -Force
    }

    $prodState = Join-Path $ProductionData "_state"
    foreach ($file in @("timelapse.sqlite", "worker.sqlite")) {
        $src = Join-Path $prodState $file
        if (Test-Path $src) {
            Copy-Item $src (Join-Path $backupRoot $file) -Force
        } else {
            Write-Warning "Production state file missing: $src"
        }
    }

    $devState = Join-Path $DevData "_state"
    New-Item -ItemType Directory -Force -Path $devState | Out-Null
    $existingDev = Get-ChildItem -Path $devState -Filter "*.sqlite" -ErrorAction SilentlyContinue
    if ($existingDev) {
        $devBackup = Join-Path $backupRoot "dev-before-overwrite"
        New-Item -ItemType Directory -Force -Path $devBackup | Out-Null
        $existingDev | Copy-Item -Destination $devBackup -Force
    }

    foreach ($file in @("timelapse.sqlite", "worker.sqlite")) {
        $src = Join-Path $prodState $file
        if (Test-Path $src) {
            Copy-Item $src (Join-Path $devState $file) -Force
        }
    }

    Write-Host "Backed up production state to $backupRoot"
    Write-Host "Copied SQLite state to $devState"
}

Set-Location $RepoRoot
Ensure-DevEnv
Assert-SafeDevEnv
New-Item -ItemType Directory -Force -Path (Join-Path $DevData "_state") | Out-Null

if ($CopyProductionState) {
    Backup-And-CopyState
} else {
    Write-Host "Skipping production DB copy. Re-run with -CopyProductionState if you need copied camera records."
}

Write-Host "Validating Compose config..."
docker compose @ComposeArgs config | Out-Null

Write-Host "Starting Windows dev stack..."
docker compose @ComposeArgs up -d --build timelapse worker worker-grpc worker-gateway

Write-Host "Dev stack status:"
docker compose @ComposeArgs ps

Write-Host "Waiting for dev endpoints..."
Wait-Http "http://localhost:18080/login" "Web"
Wait-Http "http://localhost:18081/api/health" "Worker REST"
Wait-Http "http://localhost:18082/api/health" "Worker gateway"
Wait-Tcp "localhost" 15051 "Worker gRPC"

Write-Host "Side-by-side dev stack is up. Open http://10.20.30.141:18080 from another LAN machine to compare."
